version: "3.7"

x-secrets:
  &default-secrets
  - db_password

services:
  app:
    build:
      context: ./app
      dockerfile: Dockerfile
    image: ${APP_NAME}
    env_file:
      - ./.env
    environment:
      - TZ=Asia/Jakarta
    tty: true
    secrets: *default-secrets
    ports:
      - 80:80
  db:
    image: postgres:16.0
    ports:
      - ${DB_PORT}:5432
    secrets: *default-secrets
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD_FILE: ${DB_PASSWORD_FILE}
      POSTGRES_DB: ${DB_DATABASE}
    volumes:
      - ./database:/var/lib/postgresql/data

secrets:
  db_password:
    file: ./secrets/db_password.txt